---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-snmp-exporter
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 9.18.0
    digest: sha256:4626261a653f065d8692e1562d814c596e0612b8a0647115a0eb89e21dc85798
  url: oci://ghcr.io/prometheus-community/charts/prometheus-snmp-exporter
