---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-blackbox-exporter
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 11.19.1
    digest: sha256:07bd141fe7d526a36d30cd66ea6a904865c7792c8f92026c23d975e6c701ef5f
  url: oci://ghcr.io/prometheus-community/charts/prometheus-blackbox-exporter
