---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hyperglass
spec:
  chartRef:
    kind: OCIRepository
    name: hyperglass
  interval: 1h
  values:
    podAnnotations:
      reloader.stakater.com/auto: "true"

    extraEnvFrom:
      - configMapRef:
          name: hyperglass
      - secretRef:
          name: &secret-ref hyperglass-openbao

    volumes:
      - name: &volume-config hyperglass-files
        configMap:
          name: hyperglass-files
      - name: &volume-devices hyperglass-devices
        secret:
          secretName: hyperglass-devices-openbao

    volumeMounts:
      - name: *volume-config
        mountPath: /etc/hyperglass/config.yaml
        subPath: config.yaml
        readOnly: true
      - name: *volume-devices
        mountPath: /etc/hyperglass/devices.yaml
        subPath: devices.yaml
        readOnly: true
      - name: *volume-config
        mountPath: /etc/hyperglass/directives.yaml
        subPath: directives.yaml
        readOnly: true
      - name: *volume-config
        mountPath: /etc/hyperglass/greeting.md
        subPath: greeting.md
        readOnly: true
      - name: *volume-config
        mountPath: /etc/hyperglass/unicornafk.svg
        subPath: unicornafk.svg
        readOnly: true

    route:
      main:
        enabled: true
        kind: HTTPRoute
        apiVersion: gateway.networking.k8s.io/v1
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: ASN
          gethomepage.dev/name: Hyperglass
          gethomepage.dev/description: Looking glass
        parentRefs:
          - name: external
            namespace: gateway
        hostnames:
          - lg.as212510.net

    valkey:
      auth:
        enabled: true
        usersExistingSecret: *secret-ref
        aclUsers:
          default:
            passwordKey: "HYPERGLASS_REDIS_PASSWORD"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
        prometheusRule:
          enabled: true
          rules:
            - alert: ValkeyDown
              annotations:
                summary: Valkey instance {{ "{{ $labels.instance }}" }} down
                description: Valkey instance {{ "{{ $labels.instance }}" }} is down.
              expr: |
                redis_up{service="{{ include "valkey.fullname" . }}-metrics"} == 0
              for: 2m
              labels:
                severity: error
            - alert: ValkeyMemoryHigh
              annotations:
                summary: Valkey instance {{ "{{ $labels.instance }}" }} is using too much memory
                description: |
                  Valkey instance {{ "{{ $labels.instance }}" }} is using {{ "{{ $value }}" }}% of its available memory.
              expr: |
                redis_memory_used_bytes{service="{{ include "valkey.fullname" . }}-metrics"} * 100
                /
                redis_memory_max_bytes{service="{{ include "valkey.fullname" . }}-metrics"}
                > 90 <= 100
              for: 2m
              labels:
                severity: error
            - alert: ValkeyKeyEviction
              annotations:
                summary: Valkey instance {{ "{{ $labels.instance }}" }} has evicted keys
                description: |
                  Valkey instance {{ "{{ $labels.instance }}" }} has evicted {{ "{{ $value }}" }} keys in the last 5 minutes.
              expr: |
                increase(redis_evicted_keys_total{service="{{ include "valkey.fullname" . }}-metrics"}[5m]) > 0
              for: 1s
              labels:
                severity: error
