---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: looking-glass
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.1.0
    digest: sha256:5d14d625a81361f6a06aee6c41dde5271bbe47b2de68a13c8b0b06e6dfba5222
  url: oci://ghcr.io/m0nsterrr/helm-charts/looking-glass
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/M0NsTeRRR/helm-charts.*$"
