apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: kube-prometheus-stack-kubelet
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kubelet
    k8s-app: kubelet
    kubernetes.io/service-name: kube-prometheus-stack-kubelet
addressType: IPv4
endpoints:
  - addresses:
      - 192.168.10.81
    hostname: k8s-1
  - addresses:
      - 192.168.10.82
    hostname: k8s-2
  - addresses:
      - 192.168.10.83
    hostname: k8s-3
ports:
  - name: https-metrics
    port: 10250
    protocol: TCP
