---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 90.0.0
    digest: sha256:f98cdaca8fd8f2a9a45e7bb65669fde28cd88250d37c9ab2319b64c84c7d322a
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
