---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 88.5.4
    digest: sha256:2d74cab37e82d84bf50a87e84ad9d5fa67b12d5d8ec341b134cb74b3d48e7908
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
