---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 88.6.1
    digest: sha256:98ece3e66b6fede4b1964e8a94c356786bfccd97f570a9661445cbdb15ab054d
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
