[project]
name = "homelabv3-infra"
revision = "1.0"

[profiles.default]
INFOMANIAK_TOKEN = { description = "Infomaniak token", required = true }
K3S_TOKEN = { description = "K3s bootstrap token", required = true }
MIKROTIK_USER = { description = "MikroTik user", required = true }
MIKROTIK_PASSWORD = { description = "MikroTik password", required = true }
