# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

vars:
  packer_dir: "{{.TASKDIR}}/packer"
  ansible_dir: "{{.TASKDIR}}/ansible"
  flatcar_dir: "{{.TASKDIR}}/flatcar"
  octodns_dir: "{{.TASKDIR}}/octodns"
  kubernetes_dir: "{{.TASKDIR}}/kubernetes"

includes:
  packer:
    taskfile: .taskfiles/packer
    dir: "{{.packer_dir}}"
  ansible:
    taskfile: .taskfiles/ansible
    dir: "{{.ansible_dir}}"
  flatcar:
    taskfile: .taskfiles/flatcar
    dir: "{{.flatcar_dir}}"
  octodns:
    taskfile: .taskfiles/octodns
    dir: "{{.octodns_dir}}"
  kubernetes:
    taskfile: .taskfiles/kubernetes
    dir: "{{.kubernetes_dir}}"

tasks:
  default: task -l
