# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

vars:
  ansible_dir: "{{.TASKDIR}}/ansible"
  flatcar_dir: "{{.TASKDIR}}/flatcar"
  kubernetes_dir: "{{.TASKDIR}}/kubernetes"
  octodns_dir: "{{.TASKDIR}}/octodns"

includes:
  ansible:
    taskfile: .taskfiles/ansible
    dir: "{{.ansible_dir}}"
  docs:
    taskfile: .taskfiles/docs
  flatcar:
    taskfile: .taskfiles/flatcar
    dir: "{{.flatcar_dir}}"
  kubernetes:
    taskfile: .taskfiles/kubernetes
    dir: "{{.kubernetes_dir}}"
  octodns:
    taskfile: .taskfiles/octodns
    dir: "{{.octodns_dir}}"

tasks:
  default: task -l
