apiVersion: v1
kind: ConfigMap
metadata:
  name: seerr
data:
  TZ: "Europe/Paris"
  DB_TYPE: postgres
  DB_HOST: "pooler-pw-rw.postgres.svc"
  DB_PORT: "5432"
  DB_SSL_CA: "/etc/ssl/certs/homelab.crt"
  DB_NAME: seerr
  DB_LOG_QUERIES: "false"
