apiVersion: v1
kind: ConfigMap
metadata:
  name: seerr
data:
  TZ: "Europe/Paris"
  DB_TYPE: postgres
  DB_HOST: "pooler-rw.postgres.svc"
  DB_PORT: "5432"
  DB_NAME: seerr
  DB_LOG_QUERIES: "false"
  DB_SSL_CA_FILE: /var/run/secrets/root-ca/ca.crt
  DB_SSL_CERT_FILE: /var/run/secrets/postgresql/tls.crt
  DB_SSL_KEY_FILE: /var/run/secrets/postgresql/tls.key
  DB_USE_SSL: "true"
