---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-traces-single
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-traces-single
  interval: 1h
  values:
    server:
      persistentVolume:
        size: 100Gi
      service:
        ipFamilyPolicy: "PreferDualStack"
      route:
        enabled: true
        parentRefs:
          - name: internal
            namespace: gateway
        hostnames:
          - victoria-traces.unicornafk.fr
      serviceMonitor:
        enabled: true
