---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-traces-single
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.1.10
    digest: sha256:1dec4dbd74a34430b33b50d6e7443cd1252915c9a44f4b52ec5f2f5efdb2a442
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-traces-single
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/VictoriaMetrics/helm-charts.*$"
