---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-smartctl-exporter
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.17.1
    digest: sha256:3b205562ffcb1fc6228c9216b3f1b1d6451e647cb73d02548c402e780ac8289f
  url: oci://ghcr.io/prometheus-community/charts/prometheus-smartctl-exporter
