---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: authentik
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2026.8.3
    digest: sha256:d2caf78313874d8d8f4694ff8a696e7905898f22b2481c0b50438910f8cb0a8f
  url: oci://ghcr.io/goauthentik/helm-charts/authentik
