---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: authentik
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2026.8.0
    digest: sha256:2c37fd7627418a7358b688cad0634e8b2340ab1d85a56f31be1f2275f9281e1e
  url: oci://ghcr.io/goauthentik/helm-charts/authentik
