---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: authentik
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2026.5.6
    digest: sha256:853e8b39f752cf80323399a12bde077e5e400d3bda885f1897bd82b02a49facc
  url: oci://ghcr.io/goauthentik/helm-charts/authentik
