---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sonarr-cluster
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.0@sha256:de736e9b99d1c4aeb576481f0f4221b6e76a8fe0f32fa2e159fe4f922c56c5a2

  primaryUpdateStrategy: unsupervised
  instances: 1
  enablePDB: false

  enableSuperuserAccess: false

  storage:
    size: 2Gi
    pvcTemplate:
      dataSourceRef:
        apiGroup: volsync.backube
        kind: ReplicationDestination
        name: db-restore

  bootstrap:
    initdb:
      database: sonarr
      owner: sonarr
      secret:
        name: postgres-vault
      dataChecksums: true
      encoding: UTF8

  monitoring:
    enablePodMonitor: true
