#jinja2:lstrip_blocks: True
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns-openbao
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/secretstore_v1.json
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: external-dns-openbao
spec:
  provider:
    vault:
      server: "https://openbao.openbao.svc:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-dns-internal"
          serviceAccountRef:
            name: "external-dns-openbao"
      caProvider:
        type: "ConfigMap"
        name: "homelab-ca"
        key: "ca.crt"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-openbao
spec:
  refreshInterval: "1m"
  target:
    creationPolicy: "Owner"
    deletionPolicy: "Retain"
  secretStoreRef:
    kind: SecretStore
    name: external-dns-openbao
  data:
    - secretKey: MIKROTIK_BASEURL
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: secret/data/homelab/prod/external_dns/internal
        property: MIKROTIK_BASEURL
    - secretKey: MIKROTIK_USERNAME
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: secret/data/homelab/prod/external_dns/internal
        property: MIKROTIK_USERNAME
    - secretKey: MIKROTIK_PASSWORD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: secret/data/homelab/prod/external_dns/internal
        property: MIKROTIK_PASSWORD
