---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  chartRef:
    kind: OCIRepository
    name: external-dns
  interval: 1h
  values:
    nameOverride: "external-dns-internal"
    logFormat: json
    podAnnotations:
      reloader.stakater.com/auto: "true"
    registry: txt
    txtOwnerId: "homelab.k8s"
    triggerLoopOnEvent: true
    policy: sync
    sources:
      - crd
      - gateway-httproute
      - gateway-tlsroute
      - service
    domainFilters:
      - unicornafk.fr
    extraArgs:
      - --gateway-name=internal
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --tls-ca=/etc/external-dns/ssl/ca.crt
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/mirceanton/external-dns-provider-mikrotik
          tag: v1.6.0
        env:
          - name: MIKROTIK_BASEURL
            valueFrom:
              secretKeyRef:
                name: external-dns-openbao
                key: MIKROTIK_BASEURL
          - name: MIKROTIK_CA_CERT
            value: /etc/external-dns/ssl/ca.crt
          - name: MIKROTIK_USERNAME
            valueFrom:
              secretKeyRef:
                name: external-dns-openbao
                key: MIKROTIK_USERNAME
          - name: MIKROTIK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: external-dns-openbao
                key: MIKROTIK_PASSWORD
        extraVolumeMounts:
          - name: "homelab-ca"
            mountPath: /etc/external-dns/ssl
            readOnly: true
    extraVolumes:
      - name: "homelab-ca"
        configMap:
          name: "homelab-ca"
    service:
      ipFamilyPolicy: "PreferDualStack"
    serviceMonitor:
      enabled: true
