---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "${APP}-pvc-backup"
spec:
  sourcePVC: ${APP}
  trigger:
    # At 0 minutes past the hour, every 6 hours
    schedule: "0 */6 * * *"
  restic:
    pruneIntervalDays: 14
    repository: ${APP}-volsync
    retain:
      hourly: 1
      daily: 4
      weekly: 2
      monthly: 4
      yearly: 1
    copyMethod: Snapshot
    cacheCapacity: 5Gi
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=65534}
      runAsGroup: ${VOLSYNC_PGID:=65534}
      fsGroup: ${VOLSYNC_PGID:=65534}
    customCA:
      key: ca.crt
      secretName: homelab-ca
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${APP}-pvc-restore"
spec:
  trigger:
    manual: restore-once
  restic:
    repository: ${APP}-volsync
    destinationPVC: ${APP}
    copyMethod: Direct
    accessModes: ["ReadWriteOnce"]
    cleanupCachePVC: true
    cleanupTempPVC: true
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=65534}
      runAsGroup: ${VOLSYNC_PGID:=65534}
      fsGroup: ${VOLSYNC_PGID:=65534}
    customCA:
      key: ca.crt
      secretName: homelab-ca
