---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-operator-crds
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 31.0.1
    digest: sha256:45a18cd10ce5c57cbcdd90e4eddfa9a6f653684a8d74cf6b2925f682c8a023e5
  url: oci://ghcr.io/prometheus-community/charts/prometheus-operator-crds
