---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-operator-crds
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 30.0.1
    digest: sha256:4644ce07a63e35f0d4ebcb3146908451f091e1ba521599f2bde1c6b63192b836
  url: oci://ghcr.io/prometheus-community/charts/prometheus-operator-crds
