---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: snapshot-controller
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.1.1
    digest: sha256:3e98232129b3feebee9377a6d1a3174fb6f62010a36ff2561dc80b092cae2183
  url: oci://ghcr.io/piraeusdatastore/helm-charts/snapshot-controller
