---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: snapshot-controller
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.3.0
    digest: sha256:9026d5c4c86d54ff213b53bb6cb6c854ed5648bb0bf5b32614e4f26651c465d9
  url: oci://ghcr.io/piraeusdatastore/helm-charts/snapshot-controller
