---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-gateway
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.8.2
    digest: sha256:3cad93b54cf27b6199344a324be7dac5a3ce96379538316b9ce96c56d6b9fe47
  url: oci://docker.io/envoyproxy/gateway-helm
