---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-gateway
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.9.2
    digest: sha256:80fcfff897c47ea3af290d5d9bbf2e6c4c2c0b4d740c8d60694110a977443c84
  url: oci://docker.io/envoyproxy/gateway-helm
