---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: as212510-net
spec:
  chartRef:
    kind: OCIRepository
    name: as212510-net
  interval: 1h
  values:
    extraEnvFrom:
      - configMapRef:
          name: as212510-net
      - secretRef:
          name: as212510-net-openbao

    route:
      main:
        enabled: true
        kind: HTTPRoute
        apiVersion: gateway.networking.k8s.io/v1
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: ASN
          gethomepage.dev/name: AS212510.net website
          gethomepage.dev/description: AS212510.net website
        parentRefs:
          - name: external
            namespace: gateway
        hostnames:
          - as212510.net

    serviceMonitor:
      enabled: true
