---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: metrics-server
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 3.14.0
    digest: sha256:8a9ade2972ba4a1d748da6a78a313a770dab81ebc004441b13099a2c4329ffa9
  url: oci://ghcr.io/home-operations/charts-mirror/metrics-server
