---
manager:
  include_meta: false
  max_workers: 5

processors:
  ownership:
    class: octodns.processor.ownership.OwnershipProcessor

providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./external
    default_ttl: 3600
    enforce_order: true
  infomaniak:
    class: octodns_infomaniak.InfomaniakProvider
    token: env/INFOMANIAK_TOKEN

zones:
  as212510.net.:
    sources:
      - config
    targets:
      - infomaniak
    processors:
      - ownership
  adminafk.fr.:
    sources:
      - config
    targets:
      - infomaniak
    processors:
      - ownership
  unicornafk.fr.:
    sources:
      - config
    targets:
      - infomaniak
    processors:
      - ownership
