---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: qbittorrent
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 7.1.3
    digest: sha256:756c34b8b7524106c81927d65418e1c2759c5f06d7594b8e7f85d00003d2d367
  url: oci://ghcr.io/m0nsterrr/helm-charts/qbittorrent
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/M0NsTeRRR/helm-charts.*$"
