---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  chartRef:
    kind: OCIRepository
    name: grafana
  interval: 1h
  values:
    envFromSecret: "grafana-openbao"

    annotations:
      reloader.stakater.com/auto: "true"

    extraVolumes:
      - name: &volume-ca ca-certs
        configMap:
          name: homelab-ca
    extraVolumeMounts:
      - name: *volume-ca
        mountPath: /etc/ssl/certs/homelab.crt
        subPath: ca.crt
        readOnly: true

    serviceMonitor:
      enabled: true

    service:
      ipFamilyPolicy: PreferDualStack

    admin:
      existingSecret: grafana-openbao
      userKey: ADMIN_USER
      passwordKey: ADMIN_PASSWORD

    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
      datasources:
        enabled: true
        searchNamespace: ALL
      alerts:
        enabled: true
        searchNamespace: ALL

    grafana.ini:
      analytics:
        check_for_updates: true
      server:
        root_url: "https://%(domain)s/"
      auth:
        signout_redirect_url: "https://sso.unicornafk.fr/application/o/grafana/end-session/"
        oauth_auto_login: false
      auth.generic_oauth:
        name: authentik
        enabled: true
        scopes: "openid profile email"
        auth_url: "https://sso.unicornafk.fr/application/o/authorize/"
        token_url: "https://sso.unicornafk.fr/application/o/token/"
        api_url: "https://sso.unicornafk.fr/application/o/userinfo/"
        role_attribute_path: contains(groups, 'Grafana Admins') && 'Admin' || contains(groups, 'Grafana Editors') && 'Editor' || contains(groups, 'Grafana Viewers') && 'Viewer'

    alerting:
      contactpoints.yaml:
        apiVersion: 1
        contactPoints:
          - orgId: 1
            name: &contact-receiver unicornafk
            receivers:
              - uid: unicornafk
                type: discord
                settings:
                  url: $DISCORD_WEBHOOK_URL
      policies.yaml:
        apiVersion: 1
        policies:
          - orgId: 1
            receiver: *contact-receiver
            group_by:
              - alertname

    plugins:
      - grafana-piechart-panel
      - victoriametrics-logs-datasource

    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: "default"
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            allowUiUpdates: true
            options:
              path: /var/lib/grafana/dashboards

    dashboards:
      default:
        Authentik:
          gnetId: 14837
          revision: 2
          datasource: &datasource VictoriaMetrics
        Blackbox-exporter-http:
          gnetId: 14928
          revision: 6
          datasource: *datasource
        Blackbox-exporter-icmp:
          gnetId: 20338
          revision: 3
          datasource:
            - name: DS_PROMETHEUS
              value: *datasource
        Ceph-cluster:
          gnetId: 2842
          revision: 18
          datasource: *datasource
        Ceph-osd-single:
          gnetId: 5336
          revision: 9
          datasource: *datasource
        Ceph-pools:
          gnetId: 5342
          revision: 9
          datasource: *datasource
        Ceph-openbao:
          gnetId: 12904
          revision: 2
          datasource: *datasource
        Cert-manager:
          url: https://gitlab.com/uneeq-oss/cert-manager-mixin/-/raw/master/dashboards/cert-manager.json
        Envoy-downstream:
          gnetId: 24458
          revision: 3
          datasource: *datasource
        Envoy-gateway:
          gnetId: 24460
          revision: 1
          datasource: *datasource
        Envoy-overview:
          gnetId: 24459
          revision: 3
          datasource: *datasource
        Envoy-proxy:
          gnetId: 23239
          revision: 1
          datasource: *datasource
        Envoy-upstream:
          gnetId: 24457
          revision: 4
          datasource: *datasource
        External-dns:
          gnetId: 15038
          revision: 3
          datasource: *datasource
        External-secrets:
          url: https://raw.githubusercontent.com/external-secrets/external-secrets/main/docs/snippets/dashboard.json
        Go-runtime:
          gnetId: 13240
          revision: 2
          datasource: *datasource
        FlareSolverr:
          gnetId: 19363
          revision: 1
          datasource:
            - name: DS_PROMETHEUS
              value: *datasource
        Flux2:
          gnetId: 16714
          revision: 1
          datasource:
            - name: DS_PROMETHEUS
              value: *datasource
        Routinator:
          gnetId: 11922
          revision: 7
          datasource:
            - name: DS_PROMETHEUS
              value: *datasource
        Smartctl-exporter:
          gnetId: 20204
          revision: 1
          datasource:
            - name: DS_PROMETHEUS
              value: *datasource
        Snmp-device:
          gnetId: 20347
          revision: 2
          datasource:
            - name: DS_PROMETHEUS
              value: *datasource
        Traefik:
          gnetId: 17347
          revision: 9
          datasource: *datasource
        Volsync:
          gnetId: 21356
          revision: 3
          datasource:
            - name: DS_PROMETHEUS
              value: *datasource
        VictoriaLogs:
          gnetId: 22084
          revision: 9
          datasource:
            - name: DS_PROMETHEUS
              value: *datasource
        VictoriaMetrics:
          gnetId: 10229
          revision: 48
          datasource:
            - name: DS_PROMETHEUS
              value: *datasource
        VictoriaTraces:
          gnetId: 24136
          revision: 3
          datasource:
            - name: DS_PROMETHEUS
              value: *datasource

    route:
      main:
        enabled: true
        kind: HTTPRoute
        apiVersion: gateway.networking.k8s.io/v1
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Infrastructure
          gethomepage.dev/name: Grafana
          gethomepage.dev/description: Observability platform
          gethomepage.dev/icon: grafana.png
        parentRefs:
          - name: internal
            namespace: gateway
        hostnames:
          - monitoring.unicornafk.fr
