---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: grafana
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 13.2.4
    digest: sha256:2cb1daed27df2162eef63f5a98d5298d112875121350d854ce76e014a0eb18d1
  url: oci://ghcr.io/grafana-community/helm-charts/grafana
