---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: grafana
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 12.10.4
    digest: sha256:8dc0ae7e07556c1f9f7785b395afffc19aead0575f031d4c327bfa8f142ccc59
  url: oci://ghcr.io/grafana-community/helm-charts/grafana
