---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: grafana
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 12.7.3
    digest: sha256:7444665c1b52888bc265f55e706027e4594f5e8ea4edcbbc5058cdb5d8f04c70
  url: oci://ghcr.io/grafana-community/helm-charts/grafana
