---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: prowlarr-cluster
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.0@sha256:5f67a8c8ae429c8af5692024ad58408a3f70223bf5d1cb9f9dbc36dcead88919

  primaryUpdateStrategy: unsupervised
  instances: 1
  enablePDB: false

  enableSuperuserAccess: false

  storage:
    size: 2Gi
    pvcTemplate:
      dataSourceRef:
        apiGroup: volsync.backube
        kind: ReplicationDestination
        name: db-restore

  bootstrap:
    initdb:
      database: prowlarr
      owner: prowlarr
      secret:
        name: postgres-vault
      dataChecksums: true
      encoding: UTF8

  monitoring:
    enablePodMonitor: true
