---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: prowlarr-cluster
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.0@sha256:424fc22287b7bf49e9eb87f6180e5489d0026014b1e610a4e429599d96cadb4d

  primaryUpdateStrategy: unsupervised
  instances: 1
  enablePDB: false

  enableSuperuserAccess: false

  storage:
    size: 2Gi
    pvcTemplate:
      dataSourceRef:
        apiGroup: volsync.backube
        kind: ReplicationDestination
        name: db-restore

  bootstrap:
    initdb:
      database: prowlarr
      owner: prowlarr
      secret:
        name: postgres-vault
      dataChecksums: true
      encoding: UTF8

  monitoring:
    enablePodMonitor: true
