---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: plugin-barman-cloud
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.8.0
    digest: sha256:7c6b954f627ff91e511cb2e91854cfb1b7e96df5d30208494eb5d964da47303e
  url: oci://ghcr.io/cloudnative-pg/charts/plugin-barman-cloud
