---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: plugin-barman-cloud
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.7.0
    digest: sha256:7c5e0862054294efc24bf5e31ffdb3a4ae232307fca3499b6d068c41051c07ad
  url: oci://ghcr.io/cloudnative-pg/charts/plugin-barman-cloud
