---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kured
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 6.1.0
    digest: sha256:4a8b7ae11cb1b1f847b0dba298bec32a044d91a02343e2ab4294a53100c57336
  url: oci://ghcr.io/kubereboot/charts/kured
