---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actualbudget
spec:
  chartRef:
    kind: OCIRepository
    name: actualbudget
  interval: 1h
  values:
    podAnnotations:
      reloader.stakater.com/auto: "true"

    data:
      persistence:
        volumeName: ${APP}

    route:
      main:
        enabled: true
        kind: HTTPRoute
        apiVersion: gateway.networking.k8s.io/v1
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Other
          gethomepage.dev/name: Actualbudget
          gethomepage.dev/description: Finance manager
        parentRefs:
          - name: internal
            namespace: gateway
        hostnames:
          - actualbudget.unicornafk.fr
