apiVersion: v1
kind: ConfigMap
metadata:
  name: prowlarr
data:
  TZ: "Europe/Paris"
  PROWLARR__APP__INSTANCENAME: Prowlarr
  PROWLARR__APP__THEME: dark
  PROWLARR__AUTH__METHOD: External
  PROWLARR__AUTH__REQUIRED: DisabledForLocalAddresses
  PROWLARR__LOG__DBENABLED: "False"
  PROWLARR__LOG__LEVEL: info
  PROWLARR__LOG__ANALYTICSENABLED: "False"
  PROWLARR__POSTGRES__HOST: "pooler-rw.postgres.svc"
  PROWLARR__POSTGRES__MAINDB: "prowlarr"
  PGSSLROOTCERT: /var/run/secrets/root-ca/ca.crt
  PGSSLCERT: /var/run/secrets/postgresql/tls.crt
  PGSSLKEY: /var/run/secrets/postgresql/tls.key
  PGSSLMODE: verify-full
