# Prefer IPv4 over IPv6 because I have my own ASN.
# My IPv6 prefixes are routed through a free tunnel, which is why IPv4 performs better in terms of ping and bandwidth.
precedence ::ffff:0:0/96  100
