---
manager:
  auto_arpa: true
  include_meta: false
  max_workers: 5

processors:
  ownership:
    class: octodns.processor.ownership.OwnershipProcessor

providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./internal
    default_ttl: 3600
    enforce_order: true
  mikrotik:
    class: octodns_mikrotik.MikroTikProvider
    host: r1.unicornafk.fr
    port: 443
    user: env/MIKROTIK_USER
    password: env/MIKROTIK_PASSWORD
    scheme: https
    ssl_verify: true

zones:
  unicornafk.fr.:
    sources:
      - config
    targets:
      - mikrotik
    processors:
      - ownership
