---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
spec:
  chartRef:
    kind: OCIRepository
    name: radarr
  interval: 1h
  values:
    podAnnotations:
      reloader.stakater.com/auto: "true"

    strategy:
      type: RollingUpdate

    config:
      persistence:
        enabled: false

    extraEnvFrom:
      - configMapRef:
          name: radarr
      - secretRef:
          name: radarr-openbao
    volumes:
      - name: &volume-ca ca-certs
        configMap:
          name: homelab-ca
      - name: &volume-postgres postgres-certs
        secret:
          secretName: postgres-cert-${APP}
          defaultMode: 0400
      - name: &volume-data data
        persistentVolumeClaim:
          claimName: media-storage
    volumeMounts:
      - name: *volume-ca
        mountPath: /var/run/secrets/root-ca/ca.crt
        subPath: ca.crt
        readOnly: true
      - name: *volume-postgres
        mountPath: /var/run/secrets/postgresql
        defaultMode: 0400
        readOnly: true
      - name: *volume-data
        mountPath: /movies
        subPath: movies
      - name: *volume-data
        mountPath: /downloads
        subPath: downloads
