---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: radarr
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 3.6.4
    digest: sha256:7a717d4a92e32fa704ce8f5a8416bc0f0c96c5125b7cfbf0a071d639baadc3f4
  url: oci://ghcr.io/m0nsterrr/helm-charts/radarr
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/M0NsTeRRR/helm-charts.*$"
