apiVersion: v1
kind: ConfigMap
metadata:
  name: bazarr
data:
  TZ: "Europe/Paris"
  POSTGRES_ENABLED: "True"
  POSTGRES_HOST: "pooler-rw.postgres.svc"
  POSTGRES_PORT: "5432"
  POSTGRES_DATABASE: "bazarr"
