---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chartRef:
    kind: OCIRepository
    name: cert-manager
  interval: 1h
  values:
    config:
      enableGatewayAPI: true
      enableGatewayAPIListenerSet: true
      featureGates:
        ListenerSets: true
    crds:
      enabled: true
    webhook:
      networkPolicy:
        enabled: false
      serviceIPFamilyPolicy: "PreferDualStack"
    serviceIPFamilyPolicy: "PreferDualStack"
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
