---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-${APP}
spec:
  secretName: postgres-cert-${APP}
  privateKey:
    algorithm: Ed25519
  usages:
    - client auth
  commonName: ${APP}
  issuerRef:
    name: postgres-client-ca
    kind: ClusterIssuer
