---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-${APP}
spec:
  secretName: postgres-cert-${APP}
  privateKey:
    algorithm: RSA
    size: 4096
  usages:
    - client auth
  dnsNames:
    - ${APP}
  issuerRef:
    name: cert-manager-postgres
    kind: ClusterIssuer
