---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: opentelemetry-operator
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.120.3
    digest: sha256:ba495377551cba70531d9dee067bcc2aed3c3d237ab326f2d6730074fd21a2f5
  url: oci://ghcr.io/open-telemetry/opentelemetry-helm-charts/opentelemetry-operator
