---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: opentelemetry-operator
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.122.0
    digest: sha256:1a4e7bf50d1c0db36ac34ed2c80fd96e14ad5713b73392a21642a6d579aa3631
  url: oci://ghcr.io/open-telemetry/opentelemetry-helm-charts/opentelemetry-operator
