---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  chartRef:
    kind: OCIRepository
    name: external-dns
  interval: 1h
  values:
    nameOverride: "external-dns-external"
    logFormat: json
    podAnnotations:
      reloader.stakater.com/auto: "true"
    registry: txt
    txtOwnerId: "homelab.k8s"
    triggerLoopOnEvent: true
    policy: sync
    sources:
      - crd
      - gateway-httproute
      - gateway-tlsroute
      - service
    domainFilters:
      - adminafk.fr
      - as212510.net
    extraArgs:
      - --gateway-name=external
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/m0nsterrr/external-dns-webhook-infomaniak
          tag: v0.1.3@sha256:617820029b333f72e1e5375b67d5109d8a9e8427659f8826a9450dace4f80315
        env:
          - name: INFOMANIAK_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: external-dns-openbao
                key: api-token
    service:
      ipFamilyPolicy: "PreferDualStack"
    serviceMonitor:
      enabled: true
