---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  chartRef:
    kind: OCIRepository
    name: external-dns
  interval: 1h
  values:
    nameOverride: "external-dns-external"
    logFormat: json
    podAnnotations:
      reloader.stakater.com/auto: "true"
    registry: txt
    txtOwnerId: "homelab.k8s"
    triggerLoopOnEvent: true
    policy: sync
    sources:
      - crd
      - gateway-httproute
      - gateway-tlsroute
      - service
    provider: "infomaniak"
    domainFilters:
      - adminafk.fr
      - as212510.net
    extraArgs:
      - --gateway-name=external
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
    env:
      - name: SCW_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: external-dns-openbao
            key: SCW_ACCESS_KEY
      - name: SCW_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: external-dns-openbao
            key: SCW_SECRET_KEY
    service:
      ipFamilyPolicy: "PreferDualStack"
    serviceMonitor:
      enabled: true
