#jinja2:lstrip_blocks: True
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-webhook-infomaniak-openbao
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/secretstore_v1.json
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: cert-manager-webhook-infomaniak-openbao
spec:
  provider:
    vault:
      server: "https://openbao.openbao.svc:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "cert-manager-webhook-infomaniak"
          serviceAccountRef:
            name: "cert-manager-webhook-infomaniak-openbao"
      caProvider:
        type: "ConfigMap"
        name: "homelab-ca"
        key: "ca.crt"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-webhook-infomaniak-secret-openbao
spec:
  refreshInterval: "1m"
  target:
    creationPolicy: "Owner"
    deletionPolicy: "Retain"
  secretStoreRef:
    kind: SecretStore
    name: cert-manager-webhook-infomaniak-openbao
  data:
    - secretKey: api-token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: secret/data/homelab/prod/cert_manager_webhook_infomaniak
        property: API_TOKEN
