---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: eaton-ups
spec:
  rules:
    - name: eaton.ups
      labels:
        ups.feature.node.kubernetes.io/eaton: "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            vendor: { op: In, value: ["0463", "ffff"] }
