---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${APP}-openbao
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/secretstore_v1.json
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: ${APP}-openbao
spec:
  provider:
    vault:
      server: "https://openbao.openbao.svc:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "${APP}"
          serviceAccountRef:
            name: "${APP}-openbao"
      caProvider:
        type: "ConfigMap"
        name: "homelab-ca"
        key: "ca.crt"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-postgres-openbao
spec:
  refreshInterval: "1m"
  target:
    creationPolicy: "Owner"
    deletionPolicy: "Retain"
  secretStoreRef:
    kind: SecretStore
    name: ${APP}-openbao
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: secret/data/homelab/prod/${APP}
        property: POSTGRES_USER
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: secret/data/homelab/prod/${APP}
        property: POSTGRES_PASSWORD
