---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-server-cert
spec:
  secretName: postgres-server-cert
  privateKey:
    algorithm: RSA
    size: 4096
  secretTemplate:
    labels:
      cnpg.io/reload: ""
  usages:
    - server auth
  dnsNames:
    - postgres-rw
    - postgres-ro
    - postgres-r
    - postgres-rw.postgres.svc
    - postgres-ro.postgres.svc
    - postgres-r.postgres.svc
    - postgres-rw.postgres.svc.cluster.local
    - postgres-ro.postgres.svc.cluster.local
    - postgres-r.postgres.svc.cluster.local
  issuerRef:
    name: openbao
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-client-cert
spec:
  secretName: postgres-client-cert
  privateKey:
    algorithm: RSA
    size: 4096
  secretTemplate:
    labels:
      cnpg.io/reload: ""
  usages:
    - client auth
  dnsNames:
    - streaming_replica
  issuerRef:
    name: cert-manager-postgres
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pooler-server-cert
spec:
  secretName: pooler-server-cert
  privateKey:
    algorithm: RSA
    size: 4096
  secretTemplate:
    labels:
      cnpg.io/reload: ""
  usages:
    - server auth
  dnsNames:
    - pooler-rw.postgres.svc
    - pooler-rw.svc.cluster.local
  issuerRef:
    name: openbao
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pooler-client-cert
spec:
  secretName: pooler-client-cert
  privateKey:
    algorithm: RSA
    size: 4096
  secretTemplate:
    labels:
      cnpg.io/reload: ""
  usages:
    - client auth
  dnsNames:
    - pooler-rw
  issuerRef:
    name: cert-manager-postgres
    kind: ClusterIssuer
