---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-system-trixie@sha256:c019cd482add463aa55cf53d2aedb2a50bd2c2034ff40c7938ae681f902319b5

  certificates:
    serverCASecret: postgres-server-cert
    serverTLSSecret: postgres-server-cert
    clientCASecret: postgres-client-cert
    replicationTLSSecret: postgres-client-cert

  storage:
    storageClass: ceph-block
    size: 20Gi

  # bootstrap:
  #   recovery:
  #     source: &source source

  plugins:
    - name: &plugin barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: &store rustfs-store

  # externalClusters:
  #   - name: *source
  #     plugin:
  #       name: *plugin
  #       parameters:
  #         barmanObjectName: *store
  #         serverName: postgres

  postgresql:
    pg_hba:
      - hostssl all all all cert clientcert=verify-full map=pooler-map

    pg_ident:
      - pooler-map pooler-rw all

  managed:
    roles:
      - name: authentik
        ensure: present
        login: true
        superuser: false
        disablePassword: true
      - name: bazarr
        ensure: present
        login: true
        superuser: false
        disablePassword: true
      - name: prowlarr
        ensure: present
        login: true
        superuser: false
        disablePassword: true
      - name: radarr
        ensure: present
        login: true
        superuser: false
        disablePassword: true
      - name: seerr
        ensure: present
        login: true
        superuser: false
        disablePassword: true
      - name: sonarr
        ensure: present
        login: true
        superuser: false
        disablePassword: true
