---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1-system-trixie@sha256:cc0468df48ff63a2d007818eabd1decaa68e31300b505879afe03cf6c5c5ff88

  certificates:
    serverCASecret: postgres-server-cert
    serverTLSSecret: postgres-server-cert
    clientCASecret: postgres-client-cert
    replicationTLSSecret: postgres-client-cert

  storage:
    storageClass: ceph-block
    size: 20Gi

  # bootstrap:
  #   recovery:
  #     source: &source source

  plugins:
    - name: &plugin barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: &store rustfs-store

  # externalClusters:
  #   - name: *source
  #     plugin:
  #       name: *plugin
  #       parameters:
  #         barmanObjectName: *store
  #         serverName: postgres

  postgresql:
    pg_hba:
      - hostssl all all all cert clientcert=verify-full map=pooler-map

    pg_ident:
      - pooler-map pooler-rw all

  managed:
    roles:
      - name: authentik
        ensure: present
        login: true
        superuser: false
        disablePassword: true
      - name: bazarr
        ensure: present
        login: true
        superuser: false
        disablePassword: true
      - name: prowlarr
        ensure: present
        login: true
        superuser: false
        disablePassword: true
      - name: radarr
        ensure: present
        login: true
        superuser: false
        disablePassword: true
      - name: seerr
        ensure: present
        login: true
        superuser: false
        disablePassword: true
      - name: sonarr
        ensure: present
        login: true
        superuser: false
        disablePassword: true
