---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-rw
spec:
  cluster:
    name: postgres
  type: rw
  pgbouncer:
    authQuery: "SELECT $1, NULL"

    serverCASecret:
      name: homelab-ca
    serverTLSSecret:
      name: pooler-client-cert
    clientCASecret:
      name: pooler-client-cert
    clientTLSSecret:
      name: pooler-server-cert

    parameters:
      server_tls_protocols: tlsv1.3
      auth_type: cert
      server_tls_sslmode: verify-full
      client_tls_sslmode: verify-full
      max_client_conn: "1000"
      default_pool_size: "10"

  monitoring:
    enablePodMonitor: true
