---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-rw
spec:
  cluster:
    name: postgres
  type: rw
  pgbouncer:
    authQuery: "SELECT usename, passwd FROM public.user_search($1)"
    serverCASecret:
      name: postgres-server-cert
    serverTLSSecret:
      name: postgres-server-cert
    clientCASecret:
      name: pooler-rw-cert
    clientTLSSecret:
      name: pooler-rw-cert
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
