# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

tasks:
  bootstrap:
    desc: Bootstrap kubernetes cluster
    cmd: helmfile apply -f bootstrap/helmfile.yaml --skip-diff-on-install --suppress-diff
