# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

tasks:
  bootstrap:
    desc: Bootstrap kubernetes cluster
    cmds:
      - task: update-openbao-certs
      - task: init-flux-pgp-keys
      - helmfile template -f bootstrap/crds.yaml -q | yq ea -r -e 'select(.kind == "CustomResourceDefinition")' | kubectl apply --server-side --force-conflicts -f -
      - helmfile sync -f bootstrap/apps.yaml --hide-notes

  update-openbao-certs:
    desc: Update openbao certificates
    cmds:
      - kubectl create namespace openbao --dry-run=client -o yaml | kubectl apply -f -
      - |
        kubectl -n openbao create secret generic openbao-server-tls \
          --from-file=openbao.crt=../ssl/homelab/openbao.unicornafk.fr/openbao.unicornafk.fr-fullchain.crt \
          --from-file=openbao.key=../ssl/homelab/openbao.unicornafk.fr/openbao.unicornafk.fr.key \
          --dry-run=client -o yaml | kubectl apply -f -

  init-flux-pgp-keys:
    desc: Update openbao certificates
    cmds:
      - kubectl create namespace flux-system --dry-run=client -o yaml | kubectl apply -f -
      - |
        kubectl -n flux-system create secret generic pgp-public-keys \
          --from-file=../kubernetes/apps/flux-system/flux-instance/app/ressources/M0NsTeRRR.asc \
          --from-file=../kubernetes/apps/flux-system/flux-instance/app/ressources/renovate.asc \
          --dry-run=client -o yaml | kubectl apply -f -

  configure-openbao:
    desc: Init openbao
    cmd: |
      cd ../ansible
      uv run ansible-playbook deploy_infra.yml --limit kubernetes
