---
name: Octodns
on:
  push:
    paths:
      - octodns/**
      - .github/workflows/octodns.yml
  pull_request:
permissions: {}
jobs:
  octodns-lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version-file: ".python-version"
      - name: Install the project
        run: uv sync --extra octodns
      - name: Validate octodns config
        run: |
          cd octodns
          uv run octodns-validate --config-file=./internal/config.yaml --all
          uv run octodns-validate --config-file=./external/config.yaml --all
        env:
          INFOMANIAK_TOKEN: fake_token
          MIKROTIK_USER: fake_user
          MIKROTIK_PASSWORD: fake_password
  octodns-deploy:
    name: Deploy
    if: github.ref == 'refs/heads/main'
    needs: [octodns-lint]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - parallel:
          - name: Install uv
            uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
          - name: Set up Python
            uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
            with:
              python-version-file: ".python-version"
      - name: Install the project
        run: uv sync --extra octodns
      - name: Apply octodns config
        run: |
          cd octodns
          uv run octodns-sync --config-file=./external/config.yaml --doit --force
        env:
          INFOMANIAK_TOKEN: ${{ secrets.INFOMANIAK_TOKEN }}
